version: '3.3'



services:
  flask:
    image: myflask
    container_name: myflask
    restart: always
      #volumes:
      #  - "/flask:/epg"
    ports:
      - "80:5000"

    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 384M
        reservations:
          cpus: '0.25'
          memory: 128M  
